vich_uploader:
    db_driver: orm
    
    mappings:
        document_object:
            uri_prefix: document
            upload_destination: '%kernel.project_dir%/public/document'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
