# #index:
# #    path: /
# #    controller: App\Controller\DefaultController::index
# index:
#     path: /
#     controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']


# api:
#     path: /api
#     controller: App\Controller\DefaultController::api

# login_check:
#     path:     /login_check
#     methods:  [POST]

